language: ruby
rvm:
- 2.1.2

bundler_args: --without development --path=~/.bundle
# set for bundler install all gems, except "development" group 
# and use "~/.bundle" folder for this gems

before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
# skip installing docs for gems

services:
  - redis-server

env:
  global:
  - BUNDLE_ARCHIVE="test-bundle"
  - RAILS_ENV=test
  - SPECPLAST_GMAIL_USERNAME="test@example.com"

addons:
  postgresql: "9.3"

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate:reset --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake

deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: iQVxyVujvRkoyI/vBG3IGQdN+6b0kqaFKBQIwfLXyKmFj/oiAZ1yag2mw6Yj3dpn/UjvVXme6iMK5cbsJ1wfePMUTKO40jcC57x7o25h6emxCBgvalyT+HE+lYoTvLKn3QA9OHBSBBDcB3Ikq/c7uZz6xtHrPVFC+mxZDOldMX0=
  run:
    # - "rake assets:clean"
    # - "rake assets:precompile"
    # - "pg:reset DATABASE_URL"
    - "rake db:migrate"
    - "rake db:seed"
    - restart
