language: ruby
rvm:
- 2.1.2

bundler_args: "--without development --deployment  --path=~/.bundle"

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler bundle_cache
  - bundle_cache_install

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate db:schema:load

after_script:
  - bundle_cache

env:
  global:
  - BUNDLE_ARCHIVE="test-bundle"
  - RAILS_ENV=test


addons:
  postgresql: "9.3"

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database specplast_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

deploy:
  provider: heroku
  strategy: git
  # run:
    # - "rake db:create"
    # - "rake db:migrate:reset"
    # - "rake db:seed"
    # - restart
  api_key:
    secure: iQVxyVujvRkoyI/vBG3IGQdN+6b0kqaFKBQIwfLXyKmFj/oiAZ1yag2mw6Yj3dpn/UjvVXme6iMK5cbsJ1wfePMUTKO40jcC57x7o25h6emxCBgvalyT+HE+lYoTvLKn3QA9OHBSBBDcB3Ikq/c7uZz6xtHrPVFC+mxZDOldMX0=