# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
  $.fn.datetimepicker.dates['ua'] =
    days: [
      'Неділя'
      'Понеділок'
      'Вівторок'
      'Середа'
      'Четвер'
      'П\'ятниця'
      'Субота'
      'Неділя'
    ]
    daysShort: [
      'Нед'
      'Пон'
      'Вів'
      'Сер'
      'Чет'
      'Птн'
      'Суб'
      'Нед'
    ]
    daysMin: [
      'Нд'
      'Пн'
      'Вт'
      'Ср'
      'Чт'
      'Пт'
      'Сб'
      'Нд'
    ]
    months: [
      'Січень'
      'Лютий'
      'Березень'
      'Квітень'
      'Травень'
      'Червень'
      'Липень'
      'Серпень'
      'Вересень'
      'Жовтень'
      'Листопад'
      'Грудень'
    ]
    monthsShort: [
      'Січ'
      'Лют'
      'Бер'
      'Кві'
      'Тра'
      'Чер'
      'Лип'
      'Сер'
      'Вер'
      'Жов'
      'Лис'
      'Гру'
    ]
    today: 'Сьогодні'
  return

# ---
# generated by js2coffee 2.1.0

$(document).ready ->
  $('#registry_dob, #achievement_date').datetimepicker
  return
